### ISSUE TITLE
Launching causes immediate crash on vista

### ISSUE THREAD

**Issue by MP36ctrl** [Eclipse-Community/r3dfox#141]
This is happening on vista build 6002 service pack 2

Here is some crash information:

Problem signature

Problem Event Name:	APPCRASH
Application Name:	r3dfox_esr.exe
Application Version:	115.13.0.8968
Application Timestamp:	669c9b42
Fault Module Name:	xul.dll
Fault Module Version:	115.13.0.8968
Fault Module Timestamp:	669c9b55
Exception Code:	80000003
Exception Offset:	018f1d3b
OS Version:	6.0.6002.2.2.0.256.1
Locale ID:	1033
Additional Information 1:	fd00
Additional Information 2:	ea6f5fe8924aaa756324d57f87834160
Additional Information 3:	fd00
Additional Information 4:	ea6f5fe8924aaa756324d57f87834160

**Comment by jonm58** [comment]
plz update to https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.2-2

**Comment by Vangelis66** [comment]
FWIW, I have both [v115.13.0esr-stable](https://github.com/Eclipse-Community/r3dfox/releases/tag/v115.13.0esr-stable) and latest [v128.0.3-hotfix](https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.3-hotfix) (in their "portable" **win32** distributions) running OK on a 2008-era **Vista SP2 32-bit** laptop, with ALL MS updates until EoS, plus a few WS2008 ones manually installed; below a screengrab of `128.0.3`, as I type this 😜 : 

![rf128](https://github.com/user-attachments/assets/5471e6c9-2eae-47af-8b4b-aaba3b9cbd0c)

BTW, the OP does not indicate the bitness and update level of the OS; `Win10 UCRT` + `MSVC++2015-2019` (no greater than `v14.32.31332.0`) are dependencies for `r3dfox` under **this OS** 😄 ...

**Comment by K4sum1** [comment]
Probably just missing updates
