### ISSUE TITLE
ok r3dfox is good but...

### ISSUE THREAD

**Issue by kurwaaaaa** [Eclipse-Community/r3dfox#162]
is it just me, or do hentai websites take sooo long to load on r3dfox compared to any other browser?
i'd say i masturbate every so often, so this does cause a spot of inconvenience for me, when i want to masturbate that is,
apart from that id say its a pretty good brower
chose another browser for masturbation
personally i masturbate on opera gx

**Comment by K4sum1** [comment]
Use Gelbooru and Kemono like a sane person
