### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by zooool** [Eclipse-Community/r3dfox#7]
Can you do (automated) Windows 7 releases?
I have no idea how to build this.

**Comment by K4sum1** [comment]
Not sure about automated, but I intend to publish builds here once I get it fully rebranded. I should get to doing this somewhat soon.

**Comment by spacedrone404** [comment]
> I should get to doing this somewhat soon.

Thank you so much!

**Comment by spacedrone404** [comment]
Ah, and by the way, what will be the difference between mercury and Vyvfox?

**Comment by K4sum1** [comment]
> Ah, and by the way, what will be the difference between mercury and Vyvfox?

Mercury 121 doesn't run on 7. I would like this to be a sort of basis for forking a 7 compatible Firefox.

I almost want this to just get merged with Mercury as I kinda don't know what I'm doing. I have no idea why I'm the first. If I can do it, everyone with an established Firefox fork could do it too.

**Comment by wealstarr** [comment]
> Not sure about automated, but I intend to publish builds here once I get it fully rebranded. I should get to doing this somewhat soon.

Very much appreciate the pre-complied builds. Thank you.

**Comment by acoul** [comment]
[firefox v121 for Windows 7 ](https://www.reddit.com/r/windows7/comments/18v3o8j/i_present_you_a_christmas_gift_firefox_121/)

**Comment by K4sum1** [comment]
Yeah that is it, I originally released that as a download that expired in three days. Didn't release it here since it has so much remaining Firefox branding.

**Comment by acoul** [comment]
> Yeah that is it, I originally released that as a download that expired in three days. Didn't release it here since it has so much remaining Firefox branding.

in the (good) old days, they used to say: [release early, release frequent](https://en.wikipedia.org/wiki/Release_early,_release_often)

no matter what, it remains a First :)

**Comment by adeii** [comment]
Gecko-dev is nightly branch instead of official !?
Without rebranding, I got this:
![FF1](https://github.com/Eclipse-Community/vyvfox/assets/718474/98617c03-211b-4df9-b8ca-201374873e6e)

**Comment by K4sum1** [comment]
> Gecko-dev is nightly branch instead of official !? Without rebranding, I got this: ![FF1](https://private-user-images.githubusercontent.com/718474/300016808-98617c03-211b-4df9-b8ca-201374873e6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDA0MzMsIm5iZiI6MTcwNjM0MDEzMywicGF0aCI6Ii83MTg0NzQvMzAwMDE2ODA4LTk4NjE3YzAzLTIxMWItNGRmOS1iOGNhLTIwMTM3NDg3M2U2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNzIyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODQyZWQ5NWU5MzZiYzg4MGFjZTQ2MjRiMTc5Zjc4NGU0MWVlN2I1Zjg3ZGRiZjcwMDhiMDZlOThkZmQ1NzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kXmBSqc3dKElkZlGBsvmdRyzQei9izCmgX9C6n_DQOs)

Yes gecko-dev defaults to nightly. You have to pick the release branch. If you want release but working on 7, switch this repo to the release branch. It's basically done.

**Comment by K4sum1** [comment]
Published a release of 122. Still not at the point when I would consider it perfect, but it runs on 7.

https://github.com/Eclipse-Community/r3dfox/releases/tag/122.0.1-beta

**Comment by andika207** [comment]
somebody mentioned r3dfox here https://github.com/win32ss/supermium/issues/215#issuecomment-1918776311
